"""add access requests and temporary password hash

Revision ID: 4a5dd45dddab
Revises: f61603842eec
Create Date: 2026-09-27 04:05:56.841361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5dd45dddab'
down_revision: Union[str, Sequence[str], None] = 'f61603842eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('REVIEWER_ACCESS', 'EDITOR_ACCESS', name='accessrequesttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='accessrequeststatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_approver_id'), 'access_requests', ['approver_id'], unique=False)
    op.create_index(op.f('ix_access_requests_company_id'), 'access_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_access_requests_requester_id'), 'access_requests', ['requester_id'], unique=False)
    op.add_column('users', sa.Column('temporary_password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temporary_password_hash')
    op.drop_index(op.f('ix_access_requests_requester_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_company_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_approver_id'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
