"""create registration sessions table

Revision ID: 4e56870ca7af
Revises: b8005d6ec2db
Create Date: 2026-09-27 02:32:54.744990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e56870ca7af'
down_revision: Union[str, Sequence[str], None] = 'b8005d6ec2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_token', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=False),
    sa.Column('company_type', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('country_region', sa.String(length=150), nullable=False),
    sa.Column('company_email', sa.String(length=320), nullable=False),
    sa.Column('notification_email', sa.String(length=320), nullable=True),
    sa.Column('otp_code_hash', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('otp_resend_count', sa.Integer(), nullable=False),
    sa.Column('captcha_attempts', sa.Integer(), nullable=False),
    sa.Column('captcha_refresh_count', sa.Integer(), nullable=False),
    sa.Column('captcha_verified', sa.Boolean(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_sessions_company_email'), 'registration_sessions', ['company_email'], unique=False)
    op.create_index(op.f('ix_registration_sessions_registration_token'), 'registration_sessions', ['registration_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_sessions_registration_token'), table_name='registration_sessions')
    op.drop_index(op.f('ix_registration_sessions_company_email'), table_name='registration_sessions')
    op.drop_table('registration_sessions')
    # ### end Alembic commands ###
