"""create companies table

Revision ID: 7b9b7b8a60d8
Revises: 
Create Date: 2026-09-27 01:58:43.656172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9b7b8a60d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=False),
    sa.Column('company_type', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('country_region', sa.String(length=150), nullable=False),
    sa.Column('company_email', sa.String(length=320), nullable=False),
    sa.Column('notification_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_email'), 'companies', ['company_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_email'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
