"""create company ai profiles table

Revision ID: 8ddb1c9bbb73
Revises: ea8ad04ad32a
Create Date: 2026-09-27 16:33:55.312825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddb1c9bbb73'
down_revision: Union[str, Sequence[str], None] = 'ea8ad04ad32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_ai_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('products_services', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('preferred_writing_style', sa.Text(), nullable=True),
    sa.Column('brand_voice', sa.Text(), nullable=True),
    sa.Column('marketing_goals', sa.Text(), nullable=True),
    sa.Column('company_guidelines', sa.Text(), nullable=True),
    sa.Column('upcoming_projects', sa.Text(), nullable=True),
    sa.Column('partner_companies', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_ai_profiles_company_id'), 'company_ai_profiles', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_ai_profiles_company_id'), table_name='company_ai_profiles')
    op.drop_table('company_ai_profiles')
    # ### end Alembic commands ###
