"""create company settings table

Revision ID: b8005d6ec2db
Revises: f8fca933c9ad
Create Date: 2026-09-27 02:13:39.688063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8005d6ec2db'
down_revision: Union[str, Sequence[str], None] = 'f8fca933c9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('notification_email', sa.String(length=320), nullable=True),
    sa.Column('blog_generation_enabled', sa.Boolean(), nullable=False),
    sa.Column('publishing_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_company_id'), 'company_settings', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_settings_company_id'), table_name='company_settings')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
