"""add missing tables

Revision ID: d3ae761299e9
Revises: h8c9d0e1f2a3
Create Date: 2026-10-01 01:47:20.457533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd3ae761299e9'
down_revision: Union[str, Sequence[str], None] = 'h8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'ARCHIVED', name='knowledgedocumentstatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_company_id'), 'knowledge_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_table('blog_formats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('format_definition', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_formats_company_id'), 'blog_formats', ['company_id'], unique=False)
    op.create_table('company_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.Enum('SEMANTIC', 'EPISODIC', 'PROCEDURAL', name='memorytype', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('COMPANY_PROFILE', 'EDITOR_CHAT', 'REVIEWER_FEEDBACK', 'EXPLICIT_USER', 'SYSTEM_CONFIRMED', name='memorysource', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='memoryconfidence', native_enum=False), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE', 'ACTIVE', 'SUPERSEDED', 'ARCHIVED', name='memorystatus', native_enum=False), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['company_memories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_memories_company_id'), 'company_memories', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_memories_id'), 'company_memories', ['id'], unique=False)
    op.create_index(op.f('ix_company_memories_memory_type'), 'company_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_company_memories_status'), 'company_memories', ['status'], unique=False)
    op.create_index('ix_company_memories_tenant_status', 'company_memories', ['company_id', 'status'], unique=False)
    op.create_index('ix_company_memories_tenant_type', 'company_memories', ['company_id', 'memory_type'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_company_id'), 'knowledge_chunks', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_id'), 'knowledge_chunks', ['id'], unique=False)
    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_embeddings_chunk_id'), 'knowledge_embeddings', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_knowledge_embeddings_company_id'), 'knowledge_embeddings', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_embeddings_id'), 'knowledge_embeddings', ['id'], unique=False)
    op.drop_constraint(op.f('uq_pub_job_idempotency_key'), 'blog_publication_jobs', type_='unique')
    op.create_index(op.f('ix_blog_publication_jobs_idempotency_key'), 'blog_publication_jobs', ['idempotency_key'], unique=True)
    op.add_column('blog_reviews', sa.Column('rescheduled_for', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_blog_revisions_restored_from_id'), table_name='blog_revisions')
    op.create_index(op.f('ix_blog_revisions_restored_from_revision_id'), 'blog_revisions', ['restored_from_revision_id'], unique=False)
    op.drop_constraint(op.f('uq_blogs_topic_candidate_id'), 'blogs', type_='unique')
    op.create_index(op.f('ix_company_social_insights_id'), 'company_social_insights', ['id'], unique=False)
    op.create_index(op.f('ix_external_integrations_id'), 'external_integrations', ['id'], unique=False)
    op.drop_index(op.f('ix_wordpress_connections_company_id'), table_name='wordpress_connections')
    op.create_index(op.f('ix_wordpress_connections_company_id'), 'wordpress_connections', ['company_id'], unique=True)
    op.drop_index(op.f('ix_wp_pub_records_claim_lease_until'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wp_pub_records_connection_id'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wp_pub_records_schedule_id'), table_name='wordpress_publication_records')
    op.create_index(op.f('ix_wordpress_publication_records_blog_id'), 'wordpress_publication_records', ['blog_id'], unique=False)
    op.create_index(op.f('ix_wordpress_publication_records_claim_lease_until'), 'wordpress_publication_records', ['claim_lease_until'], unique=False)
    op.create_index(op.f('ix_wordpress_publication_records_company_id'), 'wordpress_publication_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_wordpress_publication_records_connection_id'), 'wordpress_publication_records', ['connection_id'], unique=False)
    op.create_index(op.f('ix_wordpress_publication_records_last_job_id'), 'wordpress_publication_records', ['last_job_id'], unique=False)
    op.create_index(op.f('ix_wordpress_publication_records_publication_idempotency_key'), 'wordpress_publication_records', ['publication_idempotency_key'], unique=False)
    op.create_index(op.f('ix_wordpress_publication_records_revision_id'), 'wordpress_publication_records', ['revision_id'], unique=False)
    op.create_index(op.f('ix_wordpress_publication_records_schedule_id'), 'wordpress_publication_records', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_wordpress_publication_records_status'), 'wordpress_publication_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordpress_publication_records_status'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wordpress_publication_records_schedule_id'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wordpress_publication_records_revision_id'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wordpress_publication_records_publication_idempotency_key'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wordpress_publication_records_last_job_id'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wordpress_publication_records_connection_id'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wordpress_publication_records_company_id'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wordpress_publication_records_claim_lease_until'), table_name='wordpress_publication_records')
    op.drop_index(op.f('ix_wordpress_publication_records_blog_id'), table_name='wordpress_publication_records')
    op.create_index(op.f('ix_wp_pub_records_schedule_id'), 'wordpress_publication_records', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_wp_pub_records_connection_id'), 'wordpress_publication_records', ['connection_id'], unique=False)
    op.create_index(op.f('ix_wp_pub_records_claim_lease_until'), 'wordpress_publication_records', ['claim_lease_until'], unique=False)
    op.drop_index(op.f('ix_wordpress_connections_company_id'), table_name='wordpress_connections')
    op.create_index(op.f('ix_wordpress_connections_company_id'), 'wordpress_connections', ['company_id'], unique=False)
    op.drop_index(op.f('ix_external_integrations_id'), table_name='external_integrations')
    op.drop_index(op.f('ix_company_social_insights_id'), table_name='company_social_insights')
    op.create_unique_constraint(op.f('uq_blogs_topic_candidate_id'), 'blogs', ['topic_candidate_id'])
    op.drop_index(op.f('ix_blog_revisions_restored_from_revision_id'), table_name='blog_revisions')
    op.create_index(op.f('ix_blog_revisions_restored_from_id'), 'blog_revisions', ['restored_from_revision_id'], unique=False)
    op.drop_column('blog_reviews', 'rescheduled_for')
    op.drop_index(op.f('ix_blog_publication_jobs_idempotency_key'), table_name='blog_publication_jobs')
    op.create_unique_constraint(op.f('uq_pub_job_idempotency_key'), 'blog_publication_jobs', ['idempotency_key'])
    op.drop_index(op.f('ix_knowledge_embeddings_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_company_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_chunk_id'), table_name='knowledge_embeddings')
    op.drop_table('knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_chunks_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_company_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_company_memories_tenant_type', table_name='company_memories')
    op.drop_index('ix_company_memories_tenant_status', table_name='company_memories')
    op.drop_index(op.f('ix_company_memories_status'), table_name='company_memories')
    op.drop_index(op.f('ix_company_memories_memory_type'), table_name='company_memories')
    op.drop_index(op.f('ix_company_memories_id'), table_name='company_memories')
    op.drop_index(op.f('ix_company_memories_company_id'), table_name='company_memories')
    op.drop_table('company_memories')
    op.drop_index(op.f('ix_blog_formats_company_id'), table_name='blog_formats')
    op.drop_table('blog_formats')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_company_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
