"""create editor registration sessions table

Revision ID: ea8ad04ad32a
Revises: da528f77efb6
Create Date: 2026-09-27 16:08:36.228213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8ad04ad32a'
down_revision: Union[str, Sequence[str], None] = 'da528f77efb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editor_registration_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_token', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id_card_url', sa.String(length=500), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('otp_code_hash', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('otp_resend_count', sa.Integer(), nullable=False),
    sa.Column('captcha_code_hash', sa.String(length=255), nullable=True),
    sa.Column('captcha_attempts', sa.Integer(), nullable=False),
    sa.Column('captcha_refresh_count', sa.Integer(), nullable=False),
    sa.Column('captcha_verified', sa.Boolean(), nullable=False),
    sa.Column('selected_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editor_registration_sessions_company_id'), 'editor_registration_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_editor_registration_sessions_email'), 'editor_registration_sessions', ['email'], unique=False)
    op.create_index(op.f('ix_editor_registration_sessions_registration_token'), 'editor_registration_sessions', ['registration_token'], unique=True)
    op.create_index(op.f('ix_editor_registration_sessions_selected_reviewer_id'), 'editor_registration_sessions', ['selected_reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editor_registration_sessions_selected_reviewer_id'), table_name='editor_registration_sessions')
    op.drop_index(op.f('ix_editor_registration_sessions_registration_token'), table_name='editor_registration_sessions')
    op.drop_index(op.f('ix_editor_registration_sessions_email'), table_name='editor_registration_sessions')
    op.drop_index(op.f('ix_editor_registration_sessions_company_id'), table_name='editor_registration_sessions')
    op.drop_table('editor_registration_sessions')
    # ### end Alembic commands ###
