"""add captcha hash to registration sessions

Revision ID: f61603842eec
Revises: 4e56870ca7af
Create Date: 2026-09-27 02:51:08.113742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61603842eec'
down_revision: Union[str, Sequence[str], None] = '4e56870ca7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_sessions', sa.Column('captcha_code_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_sessions', 'captcha_code_hash')
    # ### end Alembic commands ###
